[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "matterbot"
dynamic = ["description", "version"]
dependencies = [
    "fastapi >=0.109.2,<1",
    "pydantic >=2.1,<3",
    "pydantic-extra-types >=2.0",
    "uplink >=0.9.7,<1",
]
